Algoritmo "semnome"
//13. Escreva um algoritmo para converter uma
//temperatura de Celsius para Fahrenheit (F = C*1,8 + 32).
Var

celsius: real
fire: real

Inicio

escreva("Escreva a temperatura em celsius: ")
leia(celsius)
escreval()

fire<- celsius * 1.8 + 32

escreva("A temperatura em Celsius é: ")
escreva(celsius)
escreval(" °C")

escreva("Convertendo para Fahrenheit fica")
escreva(fire)
escreval(" °F")


Fimalgoritmo