Algoritmo "semnome"
//12. Escreva um algoritmo para calcular o perímetro de um triângulo isósceles.
Var

ladosa: real
ladob: real
perimetro: real
Inicio

escreva("Escreva um dos lados A: ")
leia(ladosa)
escreval()
escreva("Escreva o lado B: ")
leia(ladob)
escreval()

escreva("Os dois lados As são: ")
escreval(ladosa)
escreva("O lado B é: ")
escreval(ladob)
perimetro<- 2 * ladosa + ladob

escreva("O perimetro é:")
escreval(perimetro)

Fimalgoritmo