Algoritmo "semnome"
//10. Escreva um algoritmo que o usuário digite o valor da base
//e da altura de um triângulo para calcular a sua área.
Var

base: real
altura: real
area: real
Inicio

escreva("Escreva a altura do triangulho: ")
leia(altura)
escreval()
escreva("Escreva a base do triangulo: ")
leia(base)
escreval()
area<- base * altura

escreva("A altura é: ")
escreval(altura)
escreva("A base é: ")
escreval(base)
escreva("A area total é:")
escreval(area/2)

Fimalgoritmo