Algoritmo "semnome"
//Escreva um algoritmo que receba do teclado um nome e sobrenome de
//um usuário e imprima a mensagem "Seja bem-vindo {nome} {sobrenome}".

Var

nome: caractere
sobrenome: caractere


Inicio

escreva("Escreva seu nome: ")
leia(nome)
escreval()
escreva("Escreva seu sobrenome: ")
leia(sobrenome)
escreval

escreva("Seja bem-vindo ")
escreva(nome)
escreva(" ")
escreva(sobrenome)

Fimalgoritmo