Algoritmo "semnome"
//11. Escreva um algoritmo para calcular a área de um triângulo.
Var

base: real
altura: real
area: real
Inicio

escreva("Escreva a altura do triangulho: ")
leia(altura)
escreval()
escreva("Escreva a base do triangulo: ")
leia(base)
escreval()
area<- base * altura

escreva("A altura é: ")
escreval(altura)
escreva("A base é: ")
escreval(base)
escreva("A area total é:")
escreval(area/2)

Fimalgoritmo