Algoritmo "semnome"
//15. Escreva um algoritmo para calcular a média de quatro números.
Var

n1: real
n2: real
n3: real
n4: real
todos: inteiro

Inicio

escreva("Escreva um número: ")
leia(n1)
escreval()
escreva("Escreva um número: ")
leia(n2)
escreval()
escreva("Escreva um número: ")
leia(n3)
escreval()
escreva("Escreva um número: ")
leia(n4)
escreval()

todos <- 4

escreva("A média desses números é:")
escreva((n1 + n2 + n3 + n4)/4 )


Fimalgoritmo